name: Publish packages to GHCR

on:
  push:
    tags:
      - '*'

jobs:
  publish_web_if_necessary:
    uses: keeleinstituut/tv-devops/.github/workflows/publish_if_necessary.yaml@feat/#421/allow-file-and-context-inputs-for-docker
    with:
      github_organization: ${{ github.repository_owner }}
      app_name: ${{ github.event.repository.name }}
      git_tag: ${{ github.ref_name }}
      dockerfile_path: ./docker/Dockerfile
      docker_context_path: .
      helm_chart_path: ./helm/web

  publish_filters_if_necessary:
    uses: keeleinstituut/tv-devops/.github/workflows/publish_if_necessary.yaml@feat/#421/allow-file-and-context-inputs-for-docker
    with:
      github_organization: ${{ github.repository_owner }}
      app_name: ${{ github.event.repository.name }}
      git_tag: ${{ github.ref_name }}
      dockerfile_path: ./matecat-filters/Dockerfile
      docker_context_path: ./matecat-filters
      helm_chart_path: ./helm/filters

  publish_activemq_if_necessary:
    uses: keeleinstituut/tv-devops/.github/workflows/publish_if_necessary.yaml@feat/#421/allow-file-and-context-inputs-for-docker
    with:
      github_organization: ${{ github.repository_owner }}
      app_name: ${{ github.event.repository.name }}
      git_tag: ${{ github.ref_name }}
      dockerfile_path: ./amq/Dockerfile
      docker_context_path: ./amq
      helm_chart_path: ./helm/activemq
